name: Release and publish to npm
on:
  workflow_dispatch:
    inputs:
      input_version:
        type: choice
        description: What type of release?
        options:
        - major
        - minor
        - patch

concurrency : ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Test inputs
      run: echo "Type of release:${{ github.event.inputs.input_version }} from user ${GITHUB_ACTOR}"

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: git config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Install dependencies
      run: yarn install

    - name: Authenticate with registry
      run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Run release-it
      run: npx release-it ${{ github.event.inputs.input_version }} --ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
